import { createUseStyles } from "react-jss";
import DEFAULT_THEME from "src/themes/theme";

export const useStyles = createUseStyles(() => ({
  root: {
    height: "auto",
  },
  title: {
    fontWeight: 700,
    fontSize: "18px",
    lineHeight: "24px",
    textAlign: "center",
    padding: "18px 0 16px 0",
  },
  tabOrder: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    color: DEFAULT_THEME.theme.palette.text.secondary,
    marginTop: 32,
    "&>div": {
      width: "50%",
      display: "flex",
      justifyContent: "center",
      fontSize: 18,
      fontWeight: 600,
      paddingBottom: 16,
      borderBottom: `1px solid ${DEFAULT_THEME.theme.palette.secondary.light}`,
    },
  },
  tabActive: {
    color: `${DEFAULT_THEME.theme.palette.text.dark} !important`,
    borderBottom: `2px solid ${DEFAULT_THEME.theme.palette.text.primary} !important`,
  },
  search: {
    width: "100%",
    height: "40px",
    backgroundColor: DEFAULT_THEME.theme.palette.background.default,
    alignItems: "center",
    borderRadius: "6px",
    color: DEFAULT_THEME.theme.palette.text.secondary,
    display: "flex",
    marginTop: 16,
    justifyContent: "space-between",
    position: "relative",
    "&>div": {
      "&>img": {
        margin: "0 auto",
        position: "absolute",
        top: 10,
        left: 10,
      },
    },
    "&>input": {
      width: "100%",
      outline: "none",
      caretColor: DEFAULT_THEME.theme.palette.text.primary,
      paddingLeft: "35px",
      height: "100%",
      fontSize: "14px",
      fontWeight: "400",
      lineHeight: "24px",
      boxShadow:
        "0px 1px 3px rgba(16, 24, 40, 0.1), 0px 1px 2px -1px rgba(16, 24, 40, 0.1);",
      borderRadius: "6px",
      "&::placeholder": {
        fontSize: "14px",
        fontWeight: "400",
        color: "#9CA3AF",
        lineHeight: "24px",
      },
    },
  },
  tabPromos: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    color: DEFAULT_THEME.theme.palette.text.secondary,
    marginTop: 32,
    "&>div": {
      width: "50%",
      display: "flex",
      justifyContent: "center",
      fontSize: 18,
      fontWeight: 600,
      paddingBottom: 16,
      borderBottom: `1px solid ${DEFAULT_THEME.theme.palette.secondary.light}`,
    },
  },

  // empty activity
  rootEmptyActivity: {
    paddingRight: "24px",
    paddingLeft: "24px",
  },
  content: {
    display: "flex",
    justifyContent: "space-between",
    flexDirection: "column",
    gap: "197px",
    "& img": {
      width: "100%",
      height: "214px",
      objectFit: "contain",
      margin: "0 auto",
    },
  },
  header: {
    fontWeight: 700,
    fontSize: "18px",
    lineHeight: "24px",
    textAlign: "center",
    paddingTop: "18px",
  },
  btn: {},
  titleEmptyActivity: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    "& h1": {
      fontSize: "32px",
      fontWeight: "700",
      textAlign: "center",
      lineHeight: "40px",
      color: "#374151",
      marginTop: "10px",
    },
    "& p": {
      fontSize: "16px",
      fontWeight: "400",
      textAlign: "center",
      lineHeight: "24px",
      color: "#6B7280",
      padding: "0 20px",
    },
  },

  // render activity
  rootActivityRender: {
    paddingBottom: "60px",
  },
  titleActivity: {
    paddingTop: "16px",
    fontWeight: 600,
    fontSize: "16px",
    lineHeight: "24px",
    color: DEFAULT_THEME.theme.palette.background.onBoarding,
    marginBottom: "16px",
  },
  product: {
    paddingBottom: "16px",
    width: "100%",
    display: "flex",
    justifyContent: "flex-start",
    alignItems: "center",
    gap: "8px",
    "& img": {
      width: "48px",
      height: "48px",
      borderRadius: "8px",
    },
    "& p": {
      fontWeight: 400,
      fontSize: "14px",
      color: DEFAULT_THEME.theme.palette.background.onBoarding,
      lineHeight: "24px",
    },
  },
  info: {},
  head: {
    display: "flex !important",
    flexDirection: "column",
    justifyContent: "space-between",
    lineHeight: "24px",
    "& span": {
      fontWeight: 600,
      fontSize: "14px",
      color: DEFAULT_THEME.theme.palette.text.title,
    },
  },
  footer: {
    display: "flex",
    justifyContent: "space-between",
    flexDirection: "column",
    lineHeight: "24px",
    "& span:nth-child(1)": {
      fontWeight: 400,
      fontSize: "14px",
      color: DEFAULT_THEME.theme.palette.text.cardText,
      display: "flex",
      justifyContent: "right",
      opacity: 0.5,
    },
    "& span:nth-child(2)": {
      fontWeight: 600,
      fontSize: "14px",
      color: DEFAULT_THEME.theme.palette.text.helpText,
      display: "flex",
      justifyContent: "right",
    },
  },
  time: {
    display: "flex",
    gap: "4px",
    "& span": {
      opacity: 1,
    },
  },
  imgArrowUp: {
    margin: "auto",
    objectFit: "contain",
    height: "auto",
    width: "15px",
  },
  infoProduct: {
    display: "flex",
    justifyContent: "space-between",
    width: "100%",
  },
  line: {
    height: 1,
    width: "100%",
    backgroundColor: "#E5E7EB",
  },
  arrowDownCustom: {
    width: "100%",
    cursor: "pointer",
    display: "flex",
    justifyContent: "center",
    paddingTop: 16,
    paddingBottom: "16px",
    transition: "background-color 0.6s ease;",
    "& div": {
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      gap: "5px",
      "& p": {
        fontWeight: 400,
        fontSize: "12px",
        lineHeight: "16px",
        color: "#374151",
      },
    },
  },
  imgArrowDown: {
    margin: "auto",
    objectFit: "contain",
    height: "auto",
    width: "11px",
  },
  activityInfo: {
    overflow: "hidden",
    transition: "max-height 0.6s ease;",
  },
  imgTime: {
    objectFit: "contain",
    width: "24px !important",
    height: "24px !important",
  },
  status: {
    fontWeight: "400 !important",
    fontSize: "14px",
    lineHeight: "24px",
    color: "#374151",
  },
  // activities info

  rootInfo: {
    // padding: "0 24px",
    height: "auto",
  },
  checkout: {
    display: "flex",
    justifyContent: "flex-start",
    alignItems: "center",
    paddingTop: 18,
    width: "100%",
  },
  checkoutHeader: {
    fontWeight: "700",
    fontSize: 18,
    lineHeight: "24px",
    textAlign: "center",
    color: DEFAULT_THEME.theme.palette.text.titleText,
    width: "100%",
  },
  checkoutBack: {
    "& img": {
      objectFit: "contain",
    },
  },
  driver: {
    display: "flex",
    flexDirection: "column",
  },
  infoDriver: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "8px",
  },
  contentDriver: {
    display: "flex",
    alignContent: "center",
    justifyContent: "space-between",
    width: "100%",
  },
  contentName: {
    "& p:nth-child(1)": {
      fontWeight: 600,
      fontSize: "14px",
      lineHeight: "24px",
      textAlign: "center",
      color: "#374151",
    },
    "& p:nth-child(2)": {
      fontSize: "12px",
      lineHeight: "16px",
      fontWeight: "400",
      color: "#6B7280",
    },
  },
  contentInfoDriver: {
    "& > p:first-child": {
      fontSize: "14px",
      lineHeight: "24px",
      fontWeight: "600",
      color: "#374151",
    },
    "& p:nth-child(2)": {
      fontSize: "12px",
      lineHeight: "16px",
      fontWeight: "400",
      color: "#374151",
    },
  },
  contentStar: {
    display: "flex",
    flexDirection: "column",
  },
  containedNeo: {
    display: "flex",
  },
  img: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 21,
    marginBottom: 15,
    "&:hover": {
      opacity: 0.5,
    },
  },
  imgstar: {
    display: "flex",
    justifyContent: "right",
    alignContent: "center",
    gap: "4px",
    "& img": {
      objectFit: "contain",
      width: "16px",
      height: "16px",
      position: "relative",
      transform: "translateY(20%)",
    },
    "& span": {
      fontWeight: 400,
      fontSize: "14px",
      lineHeight: "24px",
      color: "#6B7280",
    },
  },
  infoBot: {
    fontSize: "12px",
    lineHeight: "16px",
    fontWeight: "400",
    color: "#6B7280",
  },
  // title: {
  //   "& p:nth-child(1)": {
  //     fontWeight: 700,

  //     fontSize: "18px",
  //     lineHeight: "24px",
  //     textAlign: "center",
  //     color: "#374151",
  //   },
  //   "& p:nth-child(2)": {
  //     fontWeight: 400,
  //     fontSize: "12px",
  //     lineHeight: "16px",
  //     textAlign: "center",
  //     color: "#6B7280",
  //   },
  // },

  driverinfo: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  // content: {
  //   display: "flex",
  //   flexDirection: "column",
  //   "& img": {
  //     height: "56px",
  //     width: "56px",
  //     objectFit: "cover",
  //     margin: "0 auto",
  //     marginBottom: "8px",
  //   },
  //   "& span": {
  //     fontWeight: 600,
  //     fontSize: "14px",
  //     lineHeight: "24px",
  //     textAlign: "center",
  //     color: "#374151",
  //   },
  //   "& p": {
  //     fontWeight: 400,
  //     fontSize: "12px",
  //     lineHeight: "16px",
  //     textAlign: "center",
  //     color: "#6B7280",
  //   },
  // },
  bot: {
    display: "flex",
  },
  bottravel: {
    display: "flex",
    flexDirection: "column",
    rowGap: "16px",
    marginLeft: "8px",
    paddingBottom: "16px",
    marginTop: "3px",
  },
  up: {
    transform: "translateY(357px)",
    animation: "$Up 1s ease forwards ",
  },
  titleHead: {
    paddingTop: "16px",
    fontWeight: 400,
    fontSize: "12px",
    lineHeight: "16px",
    color: DEFAULT_THEME.theme.palette.text.titleText,
    marginBottom: "16px",
  },
  to: {
    fontSize: "14px",
    lineHeight: "24px",
    "& span": {
      fontWeight: 600,
      color: "#374151",
    },
    "& p": {
      fontWeight: 400,
      fontSize: "14px",
      opacity: 0.7,
    },
  },
  from: {
    fontSize: "14px",
    lineHeight: "24px",
    "& span": {
      fontWeight: 600,
      color: "#374151",
    },
    "& p": {
      fontWeight: 400,
      fontSize: "14px",
      opacity: 0.7,
    },
  },
  address: {
    maxLines: 2,
    wordWrap: "break-word",
    textOverflow: "ellipsis",
  },
  overlay: {
    position: "fixed",
    top: "0px",
    left: "0px",
    right: " 0px",
    bottom: "0px",
    backgroundColor: "black",
    opacity: 0.8,
    zIndex: 201,
    height: "100vh",
  },
  exit: {
    position: "absolute",
    top: "18px",
    right: "18px",
  },
  popup: {
    position: "fixed",
    zIndex: 201,
    left: "50%",
    top: "50%",
    width: "80%",
    height: "fit-content",
    transform: "translate(-50% , -50%)",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "white",
    borderRadius: "8px",
    "& p:nth-child(1)": {
      width: "100%",
      fontSize: "18px",
      lineHeight: "24px",
      fontWeight: "600",
      alignSelf: "center",
      color: DEFAULT_THEME.theme.palette.text.radioText,
      padding: "13px 24px",
      borderBottom: `1px solid ${DEFAULT_THEME.theme.palette.secondary.light}`,
      display: "flex",
      justifyContent: "center",
    },
    "& p:nth-child(2)": {
      width: "100%",
      alignSelf: "center",
      fontSize: "16px",
      display: "flex",
      justifyContent: "center",
      padding: "13px 24px",
      lineHeight: "16px",
      fontWeight: "400",
      color: DEFAULT_THEME.theme.palette.info.light,
    },
  },
}));
